---
  - Name:  Install Filebeat
    hosts: webservers
    become: true
    tasks:
      # Download .deb
      - name: Download filebeat.deb
        command: curl https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb -O

      # Install filebeat
      - name: Install filebeat
        command: dpkg -i filebeat-7.4.0-amd64.deb

      # Copy filebeat config
      - name: Copy config files
        copy:
          src: /etc/ansible/roles/files/filebeat-configuration.yml
          dest: /etc/filebeat/filebeat.yml

      # Setup filebeat
      - name: setup filebeat
        command: filebeat modules enable system

      # Setup Dashboard
      - name: setup dashboard
        command: filebeat setup

      - name: setup dashboard
        command: sudo service filebeat start
        
  - name: Install Metricbeat
    hosts: webservers
    become: true
    tasks:
      # Download .deb
      - name: Download metricbeat.deb
        command: curl https://artifacts.elastic.co/downloads/beats/metricbeat/m$

      # Install metricbeat
      - name: Install metricbeat
        command: dpkg -i metricbeat-7.4.0-amd64.deb

      # Copy metricbeat config
      - name: Copy config files
        copy:
          src: /etc/ansible/roles/files/metricbeat-configuration.yml
          dest: /etc/metricbeat/metricbeat.yml

      # Setup metricbeat
      - name: setup metricbeat
        command: sudo metricbeat modules enable docker

      # Setup Dashboard
      - name: setup dashboard
        command: sudo metricbeat setup

      - name: start metricbeat
        command: sudo service metricbeat start
